Chapter_11/11_04/simple_cms/config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # default route
  # may go away in future versions of Rails
  # get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Chapter_11/11_04/simple_cms/app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # self.table_name = "admin_users"

  has_and_belongs_to_many :pages

  has_many :section_edits
  has_many :sections, :through => :section_edits

end

Chapter_11/11_04/simple_cms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Chapter_11/11_04/simple_cms/app/models/page.rb
class Page < ApplicationRecord

  belongs_to :subject, { :optional => false }
  has_many :sections
  has_and_belongs_to_many :admin_users

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

Chapter_11/11_04/simple_cms/app/models/section.rb
class Section < ApplicationRecord

  belongs_to :page
  has_many :section_edits
  has_many :admin_users, :through => :section_edits

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

Chapter_11/11_04/simple_cms/app/models/section_edit.rb
class SectionEdit < ApplicationRecord

  belongs_to :admin_user
  belongs_to :section
  
end

Chapter_11/11_04/simple_cms/app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }

end

Chapter_11/11_04/simple_cms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Chapter_11/11_04/simple_cms/app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout 'application'

  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
    render('hello')
  end

  def other_hello
    redirect_to(:action => 'hello')
  end

  def lynda
    redirect_to('http://lynda.com')
  end

  def escape_output
  end

end

Chapter_11/11_04/simple_cms/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'

  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
    @page_count = Page.count + 1
    @subjects = Subject.sorted
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = "Page created successfully."
      redirect_to(pages_path)
    else
      @page_count = Page.count + 1
      @subjects = Subject.sorted
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
    @page_count = Page.count
    @subjects = Subject.sorted
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Page updated successfully."
      redirect_to(page_path(@page))
    else
      @page_count = Page.count
      @subjects = Subject.sorted
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page destroyed successfully."
    redirect_to(pages_path)
  end

  private

  def page_params
    params.require(:page).permit(:subject_id, :name, :position, :visible, :permalink)
  end

end

Chapter_11/11_04/simple_cms/app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout 'admin'

  def index
    @sections = Section.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
    @section_count = Section.count + 1
    @pages = Page.sorted
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section created successfully."
      redirect_to(sections_path)
    else
      @section_count = Section.count + 1
      @pages = Page.sorted
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.sorted
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice] = "Section updated successfully."
      redirect_to(section_path(@section))
    else
      @section_count = Section.count
      @pages = Page.sorted
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section destroyed successfully."
    redirect_to(sections_path)
  end

  private

  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
  end

end

Chapter_11/11_04/simple_cms/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'Default'})
    @subject_count = Subject.count + 1
  end

  def create
    # Instantiate a new object using form parameters
    @subject = Subject.new(subject_params)
    # Save the object
    if @subject.save
      # If save succeeds, redirect to the index action
      flash[:notice] = "Subject created successfully."
      redirect_to(subjects_path)
    else
      # If save fails, redisplay the form so user can fix problems
      @subject_count = Subject.count + 1
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    # Find a new object using form parameters
    @subject = Subject.find(params[:id])
    # Update the object
    if @subject.update_attributes(subject_params)
      # If save succeeds, redirect to the show action
      flash[:notice] = "Subject updated successfully."
      redirect_to(subject_path(@subject))
    else
      # If save fails, redisplay the form so user can fix problems
      @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end

end

Chapter_11/11_04/simple_cms/app/helpers/application_helper.rb
module ApplicationHelper

  def status_tag(boolean, options={})
    options[:true_text]  ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end


end

Chapter_11/11_04/simple_cms/app/helpers/demo_helper.rb
module DemoHelper
end

Chapter_11/11_04/simple_cms/app/helpers/pages_helper.rb
module PagesHelper
end

Chapter_11/11_04/simple_cms/app/helpers/sections_helper.rb
module SectionsHelper
end

Chapter_11/11_04/simple_cms/app/helpers/subjects_helper.rb
module SubjectsHelper
end

Chapter_11/11_04/simple_cms/app/views/sections/_form.html.erb
<table summary="Section form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Page</th>
    <td><%= f.select(:page_id, @pages.map {|p| [p.name, p.id]}) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@section_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Content type</th>
    <td>
      <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML
    </td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :size => '40x10') %></td>
  </tr>
</table>

Chapter_11/11_04/simple_cms/app/views/sections/delete.html.erb
<% @page_title = "Delete Section" %>

<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections delete">
  <h2>Delete Section</h2>

  <%= form_for(@section, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>

  <% end %>
</div>

Chapter_11/11_04/simple_cms/app/views/sections/edit.html.erb
<% @page_title = "Edit Section" %>

<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections edit">
  <h2>Update Section</h2>

  <%= form_for(@section) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>

  <% end %>
</div>

Chapter_11/11_04/simple_cms/app/views/sections/index.html.erb
<% @page_title = "All Sections" %>

<div class="sections index">
  <h2>Sections</h2>

  <%= link_to("Add New Section", new_section_path, :class => 'action new') %>

  <table class="listing" summary="Section list">
    <tr class="header">
      <th>#</th>
      <th>Page ID</th>
      <th>Section</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.page_id %></td>
      <td><%= section.name %></td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="actions">
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

Chapter_11/11_04/simple_cms/app/views/sections/new.html.erb
<% @page_title = "New Section" %>

<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections new">
  <h2>Create Section</h2>

  <%= form_for(@section) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>

  <% end %>
</div>

Chapter_11/11_04/simple_cms/app/views/sections/show.html.erb
<% @page_title = "Show Section" %>

<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections show">
  <h2>Show Section</h2>

  <table summary="Section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Page ID</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>